---
title: "Speed comparisons between gather-group_by vs map-formula list"
output: html_document
---

```{r}
devtools::load_all()
library(microbenchmark)
library(dplyr)
library(purrr)
# str(ggplot2::diamonds)

num_vars <- 50
yvars <- paste0("Y", 1:num_vars)
xvars <- paste0("X", 1:num_vars)
covars <- paste0("V", 1:8)
interaction <- covars[1]
columns <- c(yvars, xvars, covars)
random_numbers <- rnorm(1000000, sd = 2)
sample_size <- 500
smaller_data <- 
    matrix(ncol = length(columns), dimnames = list(NULL, columns)) %>% 
    as.data.frame() %>%
    imap_dfc(~ sample(random_numbers, sample_size, replace = TRUE))

sample_size <- 2000
larger_data <- 
    matrix(ncol = length(columns), dimnames = list(NULL, columns)) %>% 
    as.data.frame() %>%
    imap_dfc(~ sample(random_numbers, sample_size, replace = TRUE))


old_way <- function(data, num_variables) {
    design(data, 'glm') %>%
        add_settings() %>%
        # add_settings('id') %>%
        add_variables('yvars', yvars[1:num_variables]) %>%
        add_variables('xvars', xvars[1:num_variables]) %>%
        add_variables('covariates', covars[1:4]) %>%
        construct_old()
}

new_way <- function(data, num_variables) {
    design(data, 'glm') %>%
        add_settings() %>%
        # add_settings('id') %>%
        add_variables('yvars', yvars[1:5]) %>%
        add_variables('xvars', xvars[1:num_variables]) %>%
        add_variables('covariates', covars[1:4]) %>%
        construct()
}
```


```{r}
microbenchmark(
    old_way(smaller_data, 10),
    new_way(smaller_data, 10),
    old_way(smaller_data, 20),
    new_way(smaller_data, 20),
    times = 3
)
```

```{r}
bench::mark(
    old_way(smaller_data, 10),
    new_way(smaller_data, 10)
)
```


```{r}
bench::mark(
    old_way(larger_data, 5),
    new_way(larger_data, 5)
)
```

